// Item model
export interface Item {
  id?: string;        // auto-generated by Firestore
  title: string;
  price: number;
  imageUrl: string;   // Cloudinary URL
  sellerId: string;
  createdAt: number;  // timestamp
}
